language: ruby

rvm:
  - 2.3.1
  - 2.2
  - 2.1

before_install:
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.12.gemfile
  - gemfiles/fluentd_v0.14.gemfile

matrix:
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.12.gemfile

